name: CI / CD for game2048
on: push
env:
  mvnPackageCache: "~/.m2/repository"
jobs:
  build:
    runs-on: [ self-hosted ]
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Maven Compile
        run: |
          mvn compile
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Game2048Bin
          path: target/*
  test:
    needs: build
    runs-on: [ self-hosted ]
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Maven Compile
        run: |
          mvn test
  package:
    needs: build
    runs-on: [ self-hosted ]
    name: Package
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Maven Package
        run: |
          mvn package
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Game2048Package
          path: target/*.war
  deploy_test:
    needs: package
    runs-on: [ self-hosted ]
    name: Deploy-Test
    environment:
      name: test
      url: http://localhost:8081/game2048
    steps:
      - name: Deploy
        run: |
          cp -f target/*.war /usr/local/tomcat/webapps